config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  #get "/",to: "articles#index" 
  get "/articles", to: "articles#index"
  get "/about", to: "about#index",as: :about
  # ,as: :about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :email,presence: true , format:{with: /\A[^@\s]+@[^@\s]+\z/, message:"must be a valid email"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
        # flash[:notice] = "Successfully created..."
        # flash[:alert] = "Not created..."
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    flash[:notice] = "Successfully created..."
    flash[:alert] = "Not created..."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/about/index.html.erb
<div class="d-flex align-item-center justify-content-center">
<h1>About US!</h1>
</div>

app/views/articles/index.html.erb
<div class="d-flex align-item-center justify-content-center">
<h1>Hello Rails !</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render partial: "shared/navbar"%> 
  

  <div class="container">

    <%= render partial:"shared/flashes"%> 
    <%= yield %>

  </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
#flashes here
<% if flash[:alert] %> 
<div class="alert alert-warning mt-4">
<%= flash[:alert] %> 
</div>
<% end %> 

<% if flash[:notice] %> 
<div class="alert alert-info mt-4">
<%= flash[:notice] %> 
</div>
<% end %> 

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to "Navbar", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Home", articles_path, class: "nav-link active"%>
 
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link"%>
      
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>